server:
  port: 8381

resilience4j.circuitbreaker:
  instances:
    edu-service:
      failureRateThreshold: 10
      minimumNumberOfCalls: 5
      slidingWindowType: TIME_BASED
      slidingWindowSize: 10
      waitDurationInOpenState: 30s
      permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true

spring:
  application:
    name: edu-service

app:
  gateways:
    orcid:
      host: orcid-service
      version: v1
      url: http://${app.gateways.orcid.host}/api/${app.gateways.orcid.version}
    org:
      host: org-service
      version: v1
      url: http://${app.gateways.org.host}/api/${app.gateways.org.version}
  url:
    fetch-organization-details: ${app.gateways.org.url}/org/organization/{url}
    fetch-researcher-details: ${app.gateways.orcid.url}/orcid/researcher/{orcid}
